package com.thermoheal.ai.utils

import android.content.Context
import com.itextpdf.kernel.colors.DeviceRgb
import com.itextpdf.kernel.pdf.PdfDocument
import com.itextpdf.kernel.pdf.PdfWriter
import com.itextpdf.layout.Document
import com.itextpdf.layout.element.Paragraph
import com.itextpdf.layout.properties.TextAlignment
import com.thermoheal.ai.domain.model.UserProfile
import com.thermoheal.ai.domain.model.WeeklySummary
import java.io.File

/**
 * Generates the "Weekly Trends" PDF (section 27). Sections: user/device info,
 * monitoring period, sensor metrics, AI observations, trends, system status,
 * research disclaimer — always included, never omitted.
 */
object ReportGenerator {

    fun generateWeeklyReport(
        context: Context,
        user: UserProfile?,
        summaries: List<WeeklySummary>,
        isDemoData: Boolean
    ): File {
        val outputDir = File(context.filesDir, "reports").apply { mkdirs() }
        val file = File(outputDir, "ThermoHeal-AI_Weekly_Report_${System.currentTimeMillis()}.pdf")

        val brandTeal = DeviceRgb(11, 79, 79)
        val mutedGray = DeviceRgb(88, 112, 111)

        PdfWriter(file).use { writer ->
            PdfDocument(writer).use { pdfDoc ->
                Document(pdfDoc).use { doc ->
                    doc.add(Paragraph("ThermoHeal-AI").setFontSize(22f).setFontColor(brandTeal).setBold())
                    doc.add(Paragraph("Weekly Wellness Trends Report").setFontSize(14f).setFontColor(mutedGray))
                    if (isDemoData) {
                        doc.add(Paragraph("SIMULATED SENSOR DATA — Research Demo Mode").setFontColor(DeviceRgb(230, 162, 60)).setBold())
                    }
                    doc.add(Paragraph(" "))

                    doc.add(sectionHeader("User & Device"))
                    doc.add(Paragraph("Name: ${user?.name ?: "Guest"}"))
                    doc.add(Paragraph("Device: ThermoHeal-AI Insole (Prototype v1.0)"))

                    doc.add(sectionHeader("Monitoring Period"))
                    doc.add(Paragraph(if (summaries.isNotEmpty()) "Weeks covered: ${summaries.size}" else "No completed weeks yet."))

                    doc.add(sectionHeader("Sensor Metrics & Trends"))
                    if (summaries.isEmpty()) {
                        doc.add(Paragraph("No weekly summary data available yet."))
                    } else {
                        summaries.forEach { s ->
                            doc.add(Paragraph("Week of ${s.weekStartDate}: Avg Wellness Index ${s.avgWellnessIndex}. " +
                                "Best day: ${s.bestDay ?: "—"}. Most active: ${s.mostActiveDay ?: "—"}. " +
                                "Most stable: ${s.mostStableDay ?: "—"}. Notable trend: ${s.notableTrend ?: "None noted."}"))
                        }
                    }

                    doc.add(sectionHeader("AI Observations"))
                    doc.add(Paragraph("Generated by the prototype rule-based AI engine. Wellness insights only — not a medical diagnosis."))

                    doc.add(sectionHeader("System Status"))
                    doc.add(Paragraph("Session type: ${if (isDemoData) "DEMO (simulated)" else "REAL_DEVICE"}"))

                    doc.add(Paragraph(" "))
                    doc.add(
                        Paragraph(
                            "ThermoHeal-AI provides wellness-monitoring information and decision-support insights. " +
                                "It is not intended to diagnose, treat, cure, or prevent disease. Clinical performance, " +
                                "safety, accuracy, and regulatory requirements require appropriate validation before clinical deployment."
                        ).setFontSize(9f).setFontColor(mutedGray).setTextAlignment(TextAlignment.LEFT)
                    )
                }
            }
        }
        return file
    }

    private fun sectionHeader(title: String) =
        Paragraph(title).setFontSize(13f).setBold().setMarginTop(10f)
}
