package com.thermoheal.ai.presentation.privacy

import androidx.compose.foundation.layout.*
import androidx.compose.foundation.rememberScrollState
import androidx.compose.foundation.verticalScroll
import androidx.compose.material.icons.Icons
import androidx.compose.material.icons.filled.*
import androidx.compose.material3.*
import androidx.compose.runtime.Composable
import androidx.compose.ui.Alignment
import androidx.compose.ui.Modifier
import androidx.compose.ui.text.font.FontWeight
import androidx.compose.ui.unit.dp
import com.thermoheal.ai.ui.components.SectionHeader
import com.thermoheal.ai.ui.components.ThermoCard
import com.thermoheal.ai.ui.components.ThermoHealTopBar

private data class SafetyItem(val icon: androidx.compose.ui.graphics.vector.ImageVector, val title: String, val note: String)

private val safetyItems = listOf(
    SafetyItem(Icons.Filled.HealthAndSafety, "Skin-contact biocompatibility", "Design consideration — validation required before extended skin contact."),
    SafetyItem(Icons.Filled.WaterDrop, "Moisture-sealed electronics", "Target specification for the prototype enclosure."),
    SafetyItem(Icons.Filled.BatteryChargingFull, "Low-power operation", "Design goal to extend usable session time between charges."),
    SafetyItem(Icons.Filled.Memory, "On-device preprocessing", "Where applicable, raw signals are processed locally before storage."),
    SafetyItem(Icons.Filled.Lock, "Secure communication", "Local data is stored on-device; cloud sync (when enabled) uses HTTPS."),
)

@Composable
fun PrivacyScreen(onBack: () -> Unit) {
    Scaffold(topBar = { ThermoHealTopBar("Privacy & Safety", onBack) }) { padding ->
        Column(Modifier.fillMaxSize().padding(padding).verticalScroll(rememberScrollState()).padding(20.dp)) {

            ThermoCard(modifier = Modifier.fillMaxWidth()) {
                Text(
                    "ThermoHeal-AI is a research and wellness-monitoring prototype. Its sensor measurements and AI-generated insights are intended for monitoring and decision support only and are not intended to diagnose, treat, cure, or prevent disease.",
                    style = MaterialTheme.typography.bodyMedium
                )
                Spacer(Modifier.height(8.dp))
                Text(
                    "Clinical performance, safety, accuracy, and regulatory requirements require appropriate validation before clinical deployment.",
                    style = MaterialTheme.typography.labelSmall, color = MaterialTheme.colorScheme.onSurfaceVariant
                )
            }

            Spacer(Modifier.height(20.dp))
            SectionHeader("Safety Considerations")
            safetyItems.forEach { item ->
                ThermoCard(modifier = Modifier.fillMaxWidth().padding(bottom = 10.dp)) {
                    Row(verticalAlignment = Alignment.CenterVertically) {
                        Icon(item.icon, contentDescription = null, tint = MaterialTheme.colorScheme.primary, modifier = Modifier.size(20.dp))
                        Spacer(Modifier.width(10.dp))
                        Column {
                            Text(item.title, style = MaterialTheme.typography.bodyMedium, fontWeight = FontWeight.SemiBold)
                            Text(item.note, style = MaterialTheme.typography.bodySmall, color = MaterialTheme.colorScheme.onSurfaceVariant)
                        }
                    }
                }
            }

            Spacer(Modifier.height(10.dp))
            SectionHeader("Your Data")
            ThermoCard(modifier = Modifier.fillMaxWidth()) {
                PrivacyPoint("Sensor Data", "Pressure, temperature, moisture and gait readings are stored locally by default.")
                PrivacyPoint("Account Data", "Name, email, and profile details you provide during sign-up.")
                PrivacyPoint("AI Processing", "Insights are generated by an on-device rule-based engine in this prototype build.")
                PrivacyPoint("Data Storage", "Local (Room) by default; cloud sync is opt-in once Firebase is configured.")
            }

            Spacer(Modifier.height(90.dp))
        }
    }
}

@Composable
private fun PrivacyPoint(title: String, description: String) {
    Column(Modifier.padding(vertical = 6.dp)) {
        Text(title, style = MaterialTheme.typography.bodyMedium, fontWeight = FontWeight.Medium)
        Text(description, style = MaterialTheme.typography.bodySmall, color = MaterialTheme.colorScheme.onSurfaceVariant)
    }
}
